import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { AuthProvider } from "../contexts/authContext";


export const metadata: Metadata = {
  title: "Content Registry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative min-h-screen">
         <div className="fixed inset-0 -z-10">
            <img
                src="/hero5.png"
                alt="Background"
                className="w-full h-full object-cover"
            />
            {/* Backdrop Overlay (Light Black) */}
            <div className="absolute inset-0 bg-black/30 backdrop-blur-[2px]" />
        </div>
        <AuthProvider>
          <Header />
            {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
